binUtils_SBU = input("Enter the compile time of Binutils in minutes:")
binUtils_SBU = int(binUtils_SBU)

print("\nComplete Build Time: "+str(binUtils_SBU*3.3+
binUtils_SBU*0.1+
binUtils_SBU*1.5+
binUtils_SBU*0.2+
binUtils_SBU*0.1+
binUtils_SBU*0.3+
binUtils_SBU*0.2+
binUtils_SBU*0.3+
binUtils_SBU*0.2+
binUtils_SBU*0.1+
binUtils_SBU*0.2+
binUtils_SBU*0.1+
binUtils_SBU*0.2+
binUtils_SBU*0.1+
binUtils_SBU*0.1+
binUtils_SBU*0.1+
binUtils_SBU*0.2+
binUtils_SBU*0.1+
binUtils_SBU*0.1+
binUtils_SBU*0.4+
binUtils_SBU*4.6+
binUtils_SBU*1.0+
binUtils_SBU*0.2+
binUtils_SBU*0.6+
binUtils_SBU*0.4+
binUtils_SBU*0.2+
binUtils_SBU*0.2+
binUtils_SBU*0.1+
binUtils_SBU*0.1+
binUtils_SBU*11+
binUtils_SBU*0.1+
binUtils_SBU*0.1+
binUtils_SBU*0.1+
binUtils_SBU*0.4+
binUtils_SBU*0.1+
binUtils_SBU*0.1+
binUtils_SBU*0.3+
binUtils_SBU*0.1+
binUtils_SBU*0.1+
binUtils_SBU*2.7+
binUtils_SBU*0.2+
binUtils_SBU*0.1+
binUtils_SBU*2.2+
binUtils_SBU*0.3+
binUtils_SBU*0.2+
binUtils_SBU*0.1+
binUtils_SBU*0.1+
binUtils_SBU*0.1+
binUtils_SBU*0.1+
+binUtils_SBU*0.1+
binUtils_SBU*43+
binUtils_SBU*0.1+
binUtils_SBU*0.2+
binUtils_SBU*0.3+
binUtils_SBU*0.1+
binUtils_SBU*1.3+
binUtils_SBU*2.3+
binUtils_SBU*0.4+
binUtils_SBU*1.2+
binUtils_SBU*1.4+
binUtils_SBU*0.1+
binUtils_SBU*0.1+
binUtils_SBU*0.1+
binUtils_SBU*0.2+
binUtils_SBU*0.1+
binUtils_SBU*7.9+
binUtils_SBU*0.1+
binUtils_SBU*0.1+
binUtils_SBU*0.1+
binUtils_SBU*6.2+
binUtils_SBU*0.1+
binUtils_SBU*3.2+
binUtils_SBU*0.1+
binUtils_SBU*0.3+
binUtils_SBU*1.8+
binUtils_SBU*2.0+
binUtils_SBU*0.1+
binUtils_SBU*0.3+
binUtils_SBU*0.1+
binUtils_SBU*0.9+
binUtils_SBU*0.1+
binUtils_SBU*0.3+
binUtils_SBU*0.2+
binUtils_SBU*0.4+
binUtils_SBU*0.2+
binUtils_SBU*0.3+
binUtils_SBU*0.3+
binUtils_SBU*0.1+
binUtils_SBU*0.1+
binUtils_SBU*0.1+
binUtils_SBU*0.5+
binUtils_SBU*0.1+
binUtils_SBU*1.5+
binUtils_SBU*0.3+
binUtils_SBU*2.4+
binUtils_SBU*0.1+
binUtils_SBU*0.2+
binUtils_SBU*0.1+
binUtils_SBU*0.5+
binUtils_SBU*2.4+
binUtils_SBU*0.1+
binUtils_SBU*0.1+
binUtils_SBU*0.1+
binUtils_SBU*12)+" minutes (the real time could vary wildly due to multiple factors)")